import gymnasium as gym

# Auto-generated skill registrations
# Generated by genhrl.scripts.register_all_skills

# Task: build_stairs_seed123

# Primitive Skill: walk_to_Large_Block_for_push (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123WalkToLargeBlockForPush-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.walk_to_Large_Block_for_push.walk_to_large_block_for_push_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.walk_to_Large_Block_for_push.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_Large_Block_into_stair_base_position (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123PushLargeBlockIntoStairBasePosition-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.push_Large_Block_into_stair_base_position.push_large_block_into_stair_base_position_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.push_Large_Block_into_stair_base_position.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Medium_Block_for_push (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123WalkToMediumBlockForPush-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.walk_to_Medium_Block_for_push.walk_to_medium_block_for_push_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.walk_to_Medium_Block_for_push.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_Medium_Block_into_stair_middle_position (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123PushMediumBlockIntoStairMiddlePosition-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.push_Medium_Block_into_stair_middle_position.push_medium_block_into_stair_middle_position_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.push_Medium_Block_into_stair_middle_position.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Small_Block_for_push (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123WalkToSmallBlockForPush-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.walk_to_Small_Block_for_push.walk_to_small_block_for_push_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.walk_to_Small_Block_for_push.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_Small_Block_into_stair_top_position (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123PushSmallBlockIntoStairTopPosition-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.push_Small_Block_into_stair_top_position.push_small_block_into_stair_top_position_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.push_Small_Block_into_stair_top_position.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Large_Block_for_climb (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123WalkToLargeBlockForClimb-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.walk_to_Large_Block_for_climb.walk_to_large_block_for_climb_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.walk_to_Large_Block_for_climb.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_onto_Large_Block (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123JumpOntoLargeBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.jump_onto_Large_Block.jump_onto_large_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.jump_onto_Large_Block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Medium_Block_for_climb (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123WalkToMediumBlockForClimb-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.walk_to_Medium_Block_for_climb.walk_to_medium_block_for_climb_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.walk_to_Medium_Block_for_climb.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_onto_Medium_Block (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123JumpOntoMediumBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.jump_onto_Medium_Block.jump_onto_medium_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.jump_onto_Medium_Block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Small_Block_for_climb (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123WalkToSmallBlockForClimb-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.walk_to_Small_Block_for_climb.walk_to_small_block_for_climb_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.walk_to_Small_Block_for_climb.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_onto_Small_Block (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed123JumpOntoSmallBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.jump_onto_Small_Block.jump_onto_small_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.jump_onto_Small_Block.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: build_stairs_seed123 (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed123BuildStairsSeed123-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.build_stairs_seed123.build_stairs_seed123_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.build_stairs_seed123.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Build_Stairs (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed123BuildStairs-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.Build_Stairs.build_stairs_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.Build_Stairs.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Climb_Stairs (from build_stairs_seed123)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed123ClimbStairs-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed123.skills.Climb_Stairs.climb_stairs_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed123.skills.Climb_Stairs.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: build_stairs_seed42

# Primitive Skill: position_small_block (from build_stairs_seed42)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed42PositionSmallBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed42.skills.position_small_block.position_small_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed42.skills.position_small_block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: position_medium_block (from build_stairs_seed42)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed42PositionMediumBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed42.skills.position_medium_block.position_medium_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed42.skills.position_medium_block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: position_large_block (from build_stairs_seed42)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed42PositionLargeBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed42.skills.position_large_block.position_large_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed42.skills.position_large_block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: ascend_first_step (from build_stairs_seed42)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed42AscendFirstStep-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed42.skills.ascend_first_step.ascend_first_step_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed42.skills.ascend_first_step.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: ascend_second_step (from build_stairs_seed42)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed42AscendSecondStep-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed42.skills.ascend_second_step.ascend_second_step_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed42.skills.ascend_second_step.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: ascend_third_step (from build_stairs_seed42)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed42AscendThirdStep-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed42.skills.ascend_third_step.ascend_third_step_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed42.skills.ascend_third_step.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: build_stairs_seed42 (from build_stairs_seed42)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed42BuildStairsSeed42-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed42.skills.build_stairs_seed42.build_stairs_seed42_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed42.skills.build_stairs_seed42.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: build_stairs (from build_stairs_seed42)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed42BuildStairs-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed42.skills.build_stairs.build_stairs_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed42.skills.build_stairs.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: climb_stairs (from build_stairs_seed42)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed42ClimbStairs-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed42.skills.climb_stairs.climb_stairs_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed42.skills.climb_stairs.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: build_stairs_seed456

# Primitive Skill: walk_to_Small_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456WalkToSmallBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.walk_to_Small_Block_for_robot_interaction.walk_to_small_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.walk_to_Small_Block_for_robot_interaction.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_Small_Block_for_robot_interaction_to_base_position (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456PushSmallBlockForRobotInteractionToBasePosition-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.push_Small_Block_for_robot_interaction_to_base_position.push_small_block_for_robot_interaction_to_base_position_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.push_Small_Block_for_robot_interaction_to_base_position.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Medium_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456WalkToMediumBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.walk_to_Medium_Block_for_robot_interaction.walk_to_medium_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.walk_to_Medium_Block_for_robot_interaction.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_Medium_Block_for_robot_interaction_to_middle_position (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456PushMediumBlockForRobotInteractionToMiddlePosition-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.push_Medium_Block_for_robot_interaction_to_middle_position.push_medium_block_for_robot_interaction_to_middle_position_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.push_Medium_Block_for_robot_interaction_to_middle_position.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Large_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456WalkToLargeBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.walk_to_Large_Block_for_robot_interaction.walk_to_large_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.walk_to_Large_Block_for_robot_interaction.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_Large_Block_for_robot_interaction_to_top_position (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456PushLargeBlockForRobotInteractionToTopPosition-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.push_Large_Block_for_robot_interaction_to_top_position.push_large_block_for_robot_interaction_to_top_position_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.push_Large_Block_for_robot_interaction_to_top_position.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Small_Block_for_robot_interaction_for_climb (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456WalkToSmallBlockForRobotInteractionForClimb-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.walk_to_Small_Block_for_robot_interaction_for_climb.walk_to_small_block_for_robot_interaction_for_climb_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.walk_to_Small_Block_for_robot_interaction_for_climb.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_onto_Small_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456JumpOntoSmallBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.jump_onto_Small_Block_for_robot_interaction.jump_onto_small_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.jump_onto_Small_Block_for_robot_interaction.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Medium_Block_for_robot_interaction_for_climb (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456WalkToMediumBlockForRobotInteractionForClimb-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.walk_to_Medium_Block_for_robot_interaction_for_climb.walk_to_medium_block_for_robot_interaction_for_climb_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.walk_to_Medium_Block_for_robot_interaction_for_climb.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_onto_Medium_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456JumpOntoMediumBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.jump_onto_Medium_Block_for_robot_interaction.jump_onto_medium_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.jump_onto_Medium_Block_for_robot_interaction.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Large_Block_for_robot_interaction_for_climb (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456WalkToLargeBlockForRobotInteractionForClimb-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.walk_to_Large_Block_for_robot_interaction_for_climb.walk_to_large_block_for_robot_interaction_for_climb_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.walk_to_Large_Block_for_robot_interaction_for_climb.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_onto_Large_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotFlatBuildStairsSeed456JumpOntoLargeBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.jump_onto_Large_Block_for_robot_interaction.jump_onto_large_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.jump_onto_Large_Block_for_robot_interaction.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: build_stairs_seed456 (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed456BuildStairsSeed456-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.build_stairs_seed456.build_stairs_seed456_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.build_stairs_seed456.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Build_Stairs (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed456BuildStairs-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.Build_Stairs.build_stairs_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.Build_Stairs.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Position_Small_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed456PositionSmallBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.Position_Small_Block_for_robot_interaction.position_small_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.Position_Small_Block_for_robot_interaction.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Position_Medium_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed456PositionMediumBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.Position_Medium_Block_for_robot_interaction.position_medium_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.Position_Medium_Block_for_robot_interaction.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Position_Large_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed456PositionLargeBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.Position_Large_Block_for_robot_interaction.position_large_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.Position_Large_Block_for_robot_interaction.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Climb_Stairs (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed456ClimbStairs-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.Climb_Stairs.climb_stairs_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.Climb_Stairs.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Ascend_Small_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed456AscendSmallBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.Ascend_Small_Block_for_robot_interaction.ascend_small_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.Ascend_Small_Block_for_robot_interaction.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Ascend_Medium_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed456AscendMediumBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.Ascend_Medium_Block_for_robot_interaction.ascend_medium_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.Ascend_Medium_Block_for_robot_interaction.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Ascend_Large_Block_for_robot_interaction (from build_stairs_seed456)
gym.register(
    id="Isaac-RobotCompositeBuildStairsSeed456AscendLargeBlockForRobotInteraction-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.build_stairs_seed456.skills.Ascend_Large_Block_for_robot_interaction.ascend_large_block_for_robot_interaction_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.build_stairs_seed456.skills.Ascend_Large_Block_for_robot_interaction.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: doorway_and_goal_seed123

# Primitive Skill: walk_to_doorway_entrance (from doorway_and_goal_seed123)
gym.register(
    id="Isaac-RobotFlatDoorwayAndGoalSeed123WalkToDoorwayEntrance-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed123.skills.walk_to_doorway_entrance.walk_to_doorway_entrance_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed123.skills.walk_to_doorway_entrance.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_through_doorway (from doorway_and_goal_seed123)
gym.register(
    id="Isaac-RobotFlatDoorwayAndGoalSeed123WalkThroughDoorway-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed123.skills.walk_through_doorway.walk_through_doorway_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed123.skills.walk_through_doorway.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_clear_of_doorway (from doorway_and_goal_seed123)
gym.register(
    id="Isaac-RobotFlatDoorwayAndGoalSeed123WalkClearOfDoorway-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed123.skills.walk_clear_of_doorway.walk_clear_of_doorway_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed123.skills.walk_clear_of_doorway.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_towards_Small_Block (from doorway_and_goal_seed123)
gym.register(
    id="Isaac-RobotFlatDoorwayAndGoalSeed123WalkTowardsSmallBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed123.skills.walk_towards_Small_Block.walk_towards_small_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed123.skills.walk_towards_Small_Block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Small_Block (from doorway_and_goal_seed123)
gym.register(
    id="Isaac-RobotFlatDoorwayAndGoalSeed123WalkToSmallBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed123.skills.walk_to_Small_Block.walk_to_small_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed123.skills.walk_to_Small_Block.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: doorway_and_goal_seed123 (from doorway_and_goal_seed123)
gym.register(
    id="Isaac-RobotCompositeDoorwayAndGoalSeed123DoorwayAndGoalSeed123-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed123.skills.doorway_and_goal_seed123.doorway_and_goal_seed123_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed123.skills.doorway_and_goal_seed123.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: navigate_through_doorway (from doorway_and_goal_seed123)
gym.register(
    id="Isaac-RobotCompositeDoorwayAndGoalSeed123NavigateThroughDoorway-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed123.skills.navigate_through_doorway.navigate_through_doorway_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed123.skills.navigate_through_doorway.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: approach_goal_block (from doorway_and_goal_seed123)
gym.register(
    id="Isaac-RobotCompositeDoorwayAndGoalSeed123ApproachGoalBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed123.skills.approach_goal_block.approach_goal_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed123.skills.approach_goal_block.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: doorway_and_goal_seed42

# Primitive Skill: approach_doorway_and_align (from doorway_and_goal_seed42)
gym.register(
    id="Isaac-RobotFlatDoorwayAndGoalSeed42ApproachDoorwayAndAlign-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed42.skills.approach_doorway_and_align.approach_doorway_and_align_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed42.skills.approach_doorway_and_align.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_through_doorway (from doorway_and_goal_seed42)
gym.register(
    id="Isaac-RobotFlatDoorwayAndGoalSeed42WalkThroughDoorway-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed42.skills.walk_through_doorway.walk_through_doorway_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed42.skills.walk_through_doorway.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Small_Block (from doorway_and_goal_seed42)
gym.register(
    id="Isaac-RobotFlatDoorwayAndGoalSeed42WalkToSmallBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed42.skills.walk_to_Small_Block.walk_to_small_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed42.skills.walk_to_Small_Block.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: doorway_and_goal_seed42 (from doorway_and_goal_seed42)
gym.register(
    id="Isaac-RobotCompositeDoorwayAndGoalSeed42DoorwayAndGoalSeed42-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed42.skills.doorway_and_goal_seed42.doorway_and_goal_seed42_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed42.skills.doorway_and_goal_seed42.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Navigate_Doorway (from doorway_and_goal_seed42)
gym.register(
    id="Isaac-RobotCompositeDoorwayAndGoalSeed42NavigateDoorway-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed42.skills.Navigate_Doorway.navigate_doorway_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed42.skills.Navigate_Doorway.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Walk_to_Small_Block (from doorway_and_goal_seed42)
gym.register(
    id="Isaac-RobotCompositeDoorwayAndGoalSeed42WalkToSmallBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed42.skills.Walk_to_Small_Block.walk_to_small_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed42.skills.Walk_to_Small_Block.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: doorway_and_goal_seed456

# Primitive Skill: approach_doorway (from doorway_and_goal_seed456)
gym.register(
    id="Isaac-RobotFlatDoorwayAndGoalSeed456ApproachDoorway-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed456.skills.approach_doorway.approach_doorway_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed456.skills.approach_doorway.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_through_doorway (from doorway_and_goal_seed456)
gym.register(
    id="Isaac-RobotFlatDoorwayAndGoalSeed456WalkThroughDoorway-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed456.skills.walk_through_doorway.walk_through_doorway_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed456.skills.walk_through_doorway.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_small_block (from doorway_and_goal_seed456)
gym.register(
    id="Isaac-RobotFlatDoorwayAndGoalSeed456WalkToSmallBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed456.skills.walk_to_small_block.walk_to_small_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed456.skills.walk_to_small_block.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: doorway_and_goal_seed456 (from doorway_and_goal_seed456)
gym.register(
    id="Isaac-RobotCompositeDoorwayAndGoalSeed456DoorwayAndGoalSeed456-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed456.skills.doorway_and_goal_seed456.doorway_and_goal_seed456_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed456.skills.doorway_and_goal_seed456.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: navigate_through_doorway (from doorway_and_goal_seed456)
gym.register(
    id="Isaac-RobotCompositeDoorwayAndGoalSeed456NavigateThroughDoorway-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.doorway_and_goal_seed456.skills.navigate_through_doorway.navigate_through_doorway_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.doorway_and_goal_seed456.skills.navigate_through_doorway.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: knock_over_pillars_seed123

# Primitive Skill: knock_over_all_cylinder_columns (from knock_over_pillars_seed123)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed123KnockOverAllCylinderColumns-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed123.skills.knock_over_all_cylinder_columns.knock_over_all_cylinder_columns_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed123.skills.knock_over_all_cylinder_columns.agents:skrl_ppo_cfg.yaml",
    },
)

# Task: knock_over_pillars_seed42

# Primitive Skill: walk_to_cylinderColumn1 (from knock_over_pillars_seed42)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed42WalkToCylindercolumn1-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed42.skills.walk_to_cylinderColumn1.walk_to_cylindercolumn1_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed42.skills.walk_to_cylinderColumn1.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: knock_over_cylinderColumn1 (from knock_over_pillars_seed42)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed42KnockOverCylindercolumn1-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed42.skills.knock_over_cylinderColumn1.knock_over_cylindercolumn1_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed42.skills.knock_over_cylinderColumn1.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_cylinderColumn2 (from knock_over_pillars_seed42)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed42WalkToCylindercolumn2-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed42.skills.walk_to_cylinderColumn2.walk_to_cylindercolumn2_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed42.skills.walk_to_cylinderColumn2.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: knock_over_cylinderColumn2 (from knock_over_pillars_seed42)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed42KnockOverCylindercolumn2-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed42.skills.knock_over_cylinderColumn2.knock_over_cylindercolumn2_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed42.skills.knock_over_cylinderColumn2.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_cylinderColumn3 (from knock_over_pillars_seed42)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed42WalkToCylindercolumn3-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed42.skills.walk_to_cylinderColumn3.walk_to_cylindercolumn3_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed42.skills.walk_to_cylinderColumn3.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: knock_over_cylinderColumn3 (from knock_over_pillars_seed42)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed42KnockOverCylindercolumn3-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed42.skills.knock_over_cylinderColumn3.knock_over_cylindercolumn3_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed42.skills.knock_over_cylinderColumn3.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_cylinderColumn4 (from knock_over_pillars_seed42)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed42WalkToCylindercolumn4-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed42.skills.walk_to_cylinderColumn4.walk_to_cylindercolumn4_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed42.skills.walk_to_cylinderColumn4.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: knock_over_cylinderColumn4 (from knock_over_pillars_seed42)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed42KnockOverCylindercolumn4-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed42.skills.knock_over_cylinderColumn4.knock_over_cylindercolumn4_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed42.skills.knock_over_cylinderColumn4.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_cylinderColumn5 (from knock_over_pillars_seed42)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed42WalkToCylindercolumn5-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed42.skills.walk_to_cylinderColumn5.walk_to_cylindercolumn5_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed42.skills.walk_to_cylinderColumn5.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: knock_over_cylinderColumn5 (from knock_over_pillars_seed42)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed42KnockOverCylindercolumn5-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed42.skills.knock_over_cylinderColumn5.knock_over_cylindercolumn5_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed42.skills.knock_over_cylinderColumn5.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: knock_over_pillars_seed42 (from knock_over_pillars_seed42)
gym.register(
    id="Isaac-RobotCompositeKnockOverPillarsSeed42KnockOverPillarsSeed42-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed42.skills.knock_over_pillars_seed42.knock_over_pillars_seed42_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed42.skills.knock_over_pillars_seed42.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: knock_over_pillars_seed456

# Primitive Skill: knock_over_pillars_seed456 (from knock_over_pillars_seed456)
gym.register(
    id="Isaac-RobotFlatKnockOverPillarsSeed456KnockOverPillarsSeed456-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.knock_over_pillars_seed456.skills.knock_over_pillars_seed456.knock_over_pillars_seed456_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.knock_over_pillars_seed456.skills.knock_over_pillars_seed456.agents:skrl_ppo_cfg.yaml",
    },
)

# Task: move_three_objects_seed123

# Primitive Skill: approach_first_0_5m_cubed_block (from move_three_objects_seed123)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed123ApproachFirst05mCubedBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed123.skills.approach_first_0_5m_cubed_block.approach_first_0_5m_cubed_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed123.skills.approach_first_0_5m_cubed_block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_first_0_5m_cubed_block_towards_platform (from move_three_objects_seed123)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed123PushFirst05mCubedBlockTowardsPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed123.skills.push_first_0_5m_cubed_block_towards_platform.push_first_0_5m_cubed_block_towards_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed123.skills.push_first_0_5m_cubed_block_towards_platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_first_0_5m_cubed_block_onto_platform (from move_three_objects_seed123)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed123PushFirst05mCubedBlockOntoPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed123.skills.push_first_0_5m_cubed_block_onto_platform.push_first_0_5m_cubed_block_onto_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed123.skills.push_first_0_5m_cubed_block_onto_platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: approach_second_0_5m_cubed_block (from move_three_objects_seed123)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed123ApproachSecond05mCubedBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed123.skills.approach_second_0_5m_cubed_block.approach_second_0_5m_cubed_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed123.skills.approach_second_0_5m_cubed_block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_second_0_5m_cubed_block_towards_platform (from move_three_objects_seed123)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed123PushSecond05mCubedBlockTowardsPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed123.skills.push_second_0_5m_cubed_block_towards_platform.push_second_0_5m_cubed_block_towards_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed123.skills.push_second_0_5m_cubed_block_towards_platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_second_0_5m_cubed_block_onto_platform (from move_three_objects_seed123)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed123PushSecond05mCubedBlockOntoPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed123.skills.push_second_0_5m_cubed_block_onto_platform.push_second_0_5m_cubed_block_onto_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed123.skills.push_second_0_5m_cubed_block_onto_platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: approach_third_0_5m_cubed_block (from move_three_objects_seed123)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed123ApproachThird05mCubedBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed123.skills.approach_third_0_5m_cubed_block.approach_third_0_5m_cubed_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed123.skills.approach_third_0_5m_cubed_block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_third_0_5m_cubed_block_towards_platform (from move_three_objects_seed123)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed123PushThird05mCubedBlockTowardsPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed123.skills.push_third_0_5m_cubed_block_towards_platform.push_third_0_5m_cubed_block_towards_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed123.skills.push_third_0_5m_cubed_block_towards_platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_third_0_5m_cubed_block_onto_platform (from move_three_objects_seed123)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed123PushThird05mCubedBlockOntoPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed123.skills.push_third_0_5m_cubed_block_onto_platform.push_third_0_5m_cubed_block_onto_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed123.skills.push_third_0_5m_cubed_block_onto_platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: move_three_objects_seed123 (from move_three_objects_seed123)
gym.register(
    id="Isaac-RobotCompositeMoveThreeObjectsSeed123MoveThreeObjectsSeed123-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed123.skills.move_three_objects_seed123.move_three_objects_seed123_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed123.skills.move_three_objects_seed123.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: move_three_objects_seed42

# Primitive Skill: walk_to_cube_for_robot_to_push_1 (from move_three_objects_seed42)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed42WalkToCubeForRobotToPush1-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed42.skills.walk_to_cube_for_robot_to_push_1.walk_to_cube_for_robot_to_push_1_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed42.skills.walk_to_cube_for_robot_to_push_1.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_cube_for_robot_to_push_1_towards_platform_for_cubes (from move_three_objects_seed42)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed42PushCubeForRobotToPush1TowardsPlatformForCubes-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_1_towards_platform_for_cubes.push_cube_for_robot_to_push_1_towards_platform_for_cubes_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_1_towards_platform_for_cubes.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_cube_for_robot_to_push_1_onto_platform_for_cubes (from move_three_objects_seed42)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed42PushCubeForRobotToPush1OntoPlatformForCubes-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_1_onto_platform_for_cubes.push_cube_for_robot_to_push_1_onto_platform_for_cubes_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_1_onto_platform_for_cubes.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_cube_for_robot_to_push_2 (from move_three_objects_seed42)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed42WalkToCubeForRobotToPush2-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed42.skills.walk_to_cube_for_robot_to_push_2.walk_to_cube_for_robot_to_push_2_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed42.skills.walk_to_cube_for_robot_to_push_2.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_cube_for_robot_to_push_2_towards_platform_for_cubes (from move_three_objects_seed42)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed42PushCubeForRobotToPush2TowardsPlatformForCubes-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_2_towards_platform_for_cubes.push_cube_for_robot_to_push_2_towards_platform_for_cubes_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_2_towards_platform_for_cubes.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_cube_for_robot_to_push_2_onto_platform_for_cubes (from move_three_objects_seed42)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed42PushCubeForRobotToPush2OntoPlatformForCubes-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_2_onto_platform_for_cubes.push_cube_for_robot_to_push_2_onto_platform_for_cubes_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_2_onto_platform_for_cubes.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_cube_for_robot_to_push_3 (from move_three_objects_seed42)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed42WalkToCubeForRobotToPush3-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed42.skills.walk_to_cube_for_robot_to_push_3.walk_to_cube_for_robot_to_push_3_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed42.skills.walk_to_cube_for_robot_to_push_3.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_cube_for_robot_to_push_3_towards_platform_for_cubes (from move_three_objects_seed42)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed42PushCubeForRobotToPush3TowardsPlatformForCubes-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_3_towards_platform_for_cubes.push_cube_for_robot_to_push_3_towards_platform_for_cubes_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_3_towards_platform_for_cubes.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_cube_for_robot_to_push_3_onto_platform_for_cubes (from move_three_objects_seed42)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed42PushCubeForRobotToPush3OntoPlatformForCubes-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_3_onto_platform_for_cubes.push_cube_for_robot_to_push_3_onto_platform_for_cubes_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed42.skills.push_cube_for_robot_to_push_3_onto_platform_for_cubes.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: move_three_objects_seed42 (from move_three_objects_seed42)
gym.register(
    id="Isaac-RobotCompositeMoveThreeObjectsSeed42MoveThreeObjectsSeed42-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed42.skills.move_three_objects_seed42.move_three_objects_seed42_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed42.skills.move_three_objects_seed42.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: move_three_objects_seed456

# Primitive Skill: walk_to_First_0_5m_cubed_block (from move_three_objects_seed456)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed456WalkToFirst05mCubedBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed456.skills.walk_to_First_0_5m_cubed_block.walk_to_first_0_5m_cubed_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed456.skills.walk_to_First_0_5m_cubed_block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_First_0_5m_cubed_block_towards_Platform (from move_three_objects_seed456)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed456PushFirst05mCubedBlockTowardsPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed456.skills.push_First_0_5m_cubed_block_towards_Platform.push_first_0_5m_cubed_block_towards_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed456.skills.push_First_0_5m_cubed_block_towards_Platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: adjust_First_0_5m_cubed_block_on_Platform (from move_three_objects_seed456)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed456AdjustFirst05mCubedBlockOnPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed456.skills.adjust_First_0_5m_cubed_block_on_Platform.adjust_first_0_5m_cubed_block_on_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed456.skills.adjust_First_0_5m_cubed_block_on_Platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Second_0_5m_cubed_block (from move_three_objects_seed456)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed456WalkToSecond05mCubedBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed456.skills.walk_to_Second_0_5m_cubed_block.walk_to_second_0_5m_cubed_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed456.skills.walk_to_Second_0_5m_cubed_block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_Second_0_5m_cubed_block_towards_Platform (from move_three_objects_seed456)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed456PushSecond05mCubedBlockTowardsPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed456.skills.push_Second_0_5m_cubed_block_towards_Platform.push_second_0_5m_cubed_block_towards_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed456.skills.push_Second_0_5m_cubed_block_towards_Platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: adjust_Second_0_5m_cubed_block_on_Platform (from move_three_objects_seed456)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed456AdjustSecond05mCubedBlockOnPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed456.skills.adjust_Second_0_5m_cubed_block_on_Platform.adjust_second_0_5m_cubed_block_on_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed456.skills.adjust_Second_0_5m_cubed_block_on_Platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_Third_0_5m_cubed_block (from move_three_objects_seed456)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed456WalkToThird05mCubedBlock-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed456.skills.walk_to_Third_0_5m_cubed_block.walk_to_third_0_5m_cubed_block_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed456.skills.walk_to_Third_0_5m_cubed_block.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_Third_0_5m_cubed_block_towards_Platform (from move_three_objects_seed456)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed456PushThird05mCubedBlockTowardsPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed456.skills.push_Third_0_5m_cubed_block_towards_Platform.push_third_0_5m_cubed_block_towards_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed456.skills.push_Third_0_5m_cubed_block_towards_Platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: adjust_Third_0_5m_cubed_block_on_Platform (from move_three_objects_seed456)
gym.register(
    id="Isaac-RobotFlatMoveThreeObjectsSeed456AdjustThird05mCubedBlockOnPlatform-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed456.skills.adjust_Third_0_5m_cubed_block_on_Platform.adjust_third_0_5m_cubed_block_on_platform_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed456.skills.adjust_Third_0_5m_cubed_block_on_Platform.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: move_three_objects_seed456 (from move_three_objects_seed456)
gym.register(
    id="Isaac-RobotCompositeMoveThreeObjectsSeed456MoveThreeObjectsSeed456-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.move_three_objects_seed456.skills.move_three_objects_seed456.move_three_objects_seed456_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.move_three_objects_seed456.skills.move_three_objects_seed456.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: obstacle_course_seed123

# Primitive Skill: walk_to_lowWall (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed123WalkToLowwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.walk_to_lowWall.walk_to_lowwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.walk_to_lowWall.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_over_lowWall (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed123JumpOverLowwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.jump_over_lowWall.jump_over_lowwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.jump_over_lowWall.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: stabilize_after_jump (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed123StabilizeAfterJump-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.stabilize_after_jump.stabilize_after_jump_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.stabilize_after_jump.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_largeSphere (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed123WalkToLargesphere-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.walk_to_largeSphere.walk_to_largesphere_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.walk_to_largeSphere.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_largeSphere_into_highWall (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed123PushLargesphereIntoHighwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.push_largeSphere_into_highWall.push_largesphere_into_highwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.push_largeSphere_into_highWall.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_smallSphere (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed123WalkToSmallsphere-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.walk_to_smallSphere.walk_to_smallsphere_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.walk_to_smallSphere.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: kick_smallSphere_away_from_wall (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed123KickSmallsphereAwayFromWall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.kick_smallSphere_away_from_wall.kick_smallsphere_away_from_wall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.kick_smallSphere_away_from_wall.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_blockCube (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed123WalkToBlockcube-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.walk_to_blockCube.walk_to_blockcube_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.walk_to_blockCube.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_on_top_of_blockCube (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed123JumpOnTopOfBlockcube-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.jump_on_top_of_blockCube.jump_on_top_of_blockcube_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.jump_on_top_of_blockCube.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: obstacle_course_seed123 (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed123ObstacleCourseSeed123-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.obstacle_course_seed123.obstacle_course_seed123_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.obstacle_course_seed123.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Navigate_and_Jump_Over_LowWall (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed123NavigateAndJumpOverLowwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.Navigate_and_Jump_Over_LowWall.navigate_and_jump_over_lowwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.Navigate_and_Jump_Over_LowWall.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Push_LargeSphere_Into_HighWall (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed123PushLargesphereIntoHighwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.Push_LargeSphere_Into_HighWall.push_largesphere_into_highwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.Push_LargeSphere_Into_HighWall.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Kick_SmallSphere_Away_From_Wall (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed123KickSmallsphereAwayFromWall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.Kick_SmallSphere_Away_From_Wall.kick_smallsphere_away_from_wall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.Kick_SmallSphere_Away_From_Wall.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Navigate_and_Jump_On_BlockCube (from obstacle_course_seed123)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed123NavigateAndJumpOnBlockcube-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed123.skills.Navigate_and_Jump_On_BlockCube.navigate_and_jump_on_blockcube_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed123.skills.Navigate_and_Jump_On_BlockCube.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: obstacle_course_seed42

# Primitive Skill: walk_to_lowWall (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed42WalkToLowwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.walk_to_lowWall.walk_to_lowwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.walk_to_lowWall.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_over_lowWall (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed42JumpOverLowwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.jump_over_lowWall.jump_over_lowwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.jump_over_lowWall.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: stabilize_after_jump (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed42StabilizeAfterJump-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.stabilize_after_jump.stabilize_after_jump_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.stabilize_after_jump.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_largeSphere (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed42WalkToLargesphere-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.walk_to_largeSphere.walk_to_largesphere_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.walk_to_largeSphere.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_largeSphere_towards_highWall (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed42PushLargesphereTowardsHighwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.push_largeSphere_towards_highWall.push_largesphere_towards_highwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.push_largeSphere_towards_highWall.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_smallSphere (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed42WalkToSmallsphere-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.walk_to_smallSphere.walk_to_smallsphere_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.walk_to_smallSphere.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: kick_smallSphere (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed42KickSmallsphere-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.kick_smallSphere.kick_smallsphere_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.kick_smallSphere.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_blockCube (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed42WalkToBlockcube-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.walk_to_blockCube.walk_to_blockcube_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.walk_to_blockCube.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_on_top_of_blockCube (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed42JumpOnTopOfBlockcube-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.jump_on_top_of_blockCube.jump_on_top_of_blockcube_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.jump_on_top_of_blockCube.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: stabilize_on_blockCube (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed42StabilizeOnBlockcube-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.stabilize_on_blockCube.stabilize_on_blockcube_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.stabilize_on_blockCube.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: obstacle_course_seed42 (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed42ObstacleCourseSeed42-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.obstacle_course_seed42.obstacle_course_seed42_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.obstacle_course_seed42.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: OvercomeLowWall (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed42Overcomelowwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.OvercomeLowWall.overcomelowwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.OvercomeLowWall.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: PushLargeSphere (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed42Pushlargesphere-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.PushLargeSphere.pushlargesphere_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.PushLargeSphere.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: KickSmallSphere (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed42Kicksmallsphere-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.KickSmallSphere.kicksmallsphere_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.KickSmallSphere.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: JumpOnBlockCube (from obstacle_course_seed42)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed42Jumponblockcube-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed42.skills.JumpOnBlockCube.jumponblockcube_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed42.skills.JumpOnBlockCube.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Task: obstacle_course_seed456

# Primitive Skill: walk_to_lowWall (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed456WalkToLowwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.walk_to_lowWall.walk_to_lowwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.walk_to_lowWall.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_over_lowWall (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed456JumpOverLowwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.jump_over_lowWall.jump_over_lowwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.jump_over_lowWall.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_largeSphere (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed456WalkToLargesphere-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.walk_to_largeSphere.walk_to_largesphere_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.walk_to_largeSphere.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: push_largeSphere_towards_highWall (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed456PushLargesphereTowardsHighwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.push_largeSphere_towards_highWall.push_largesphere_towards_highwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.push_largeSphere_towards_highWall.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_smallSphere (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed456WalkToSmallsphere-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.walk_to_smallSphere.walk_to_smallsphere_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.walk_to_smallSphere.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: kick_smallSphere_away_from_wall (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed456KickSmallsphereAwayFromWall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.kick_smallSphere_away_from_wall.kick_smallsphere_away_from_wall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.kick_smallSphere_away_from_wall.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: walk_to_blockCube (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed456WalkToBlockcube-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.walk_to_blockCube.walk_to_blockcube_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.walk_to_blockCube.agents:skrl_ppo_cfg.yaml",
    },
)

# Primitive Skill: jump_on_top_of_blockCube (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotFlatObstacleCourseSeed456JumpOnTopOfBlockcube-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.jump_on_top_of_blockCube.jump_on_top_of_blockcube_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.jump_on_top_of_blockCube.agents:skrl_ppo_cfg.yaml",
    },
)

# Composite Skill: obstacle_course_seed456 (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed456ObstacleCourseSeed456-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.obstacle_course_seed456.obstacle_course_seed456_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.obstacle_course_seed456.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Navigate_and_Jump_Over_LowWall (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed456NavigateAndJumpOverLowwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.Navigate_and_Jump_Over_LowWall.navigate_and_jump_over_lowwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.Navigate_and_Jump_Over_LowWall.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Push_LargeSphere_to_Topple_HighWall (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed456PushLargesphereToToppleHighwall-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.Push_LargeSphere_to_Topple_HighWall.push_largesphere_to_topple_highwall_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.Push_LargeSphere_to_Topple_HighWall.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Kick_SmallSphere_Away (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed456KickSmallsphereAway-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.Kick_SmallSphere_Away.kick_smallsphere_away_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.Kick_SmallSphere_Away.agents:skrl_ppo_l1_cfg.yaml",
    },
)

# Composite Skill: Jump_On_Top_of_BlockCube (from obstacle_course_seed456)
gym.register(
    id="Isaac-RobotCompositeObstacleCourseSeed456JumpOnTopOfBlockcube-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": "isaaclab_tasks.manager_based.G1_generated.skills.obstacle_course_seed456.skills.Jump_On_Top_of_BlockCube.jump_on_top_of_blockcube_cfg:RobotFlatEnvCfg",
        "skrl_cfg_entry_point": f"{__name__}.skills.obstacle_course_seed456.skills.Jump_On_Top_of_BlockCube.agents:skrl_ppo_l1_cfg.yaml",
    },
)


# --- Auto-register Flat PPO variants for composite skills ---
# For each composite registration above, also register an alias with '-Flat' suffix
# that uses the standard PPO config (agents/skrl_ppo_cfg.yaml). This enables flat PPO
# training on composite environments without hierarchical components.
try:
    import re
    import os
    _this_file = __file__
    with open(_this_file, 'r') as _f:
        _text = _f.read()
    # Find composite gym.register blocks and capture id, env_cfg_entry_point, skrl_cfg_entry_point
    _pattern = re.compile(
        r'gym\.register\(\s*id="(Isaac-RobotComposite[^"]+?-v0)"[\s\S]*?"env_cfg_entry_point":\s*"([^"]+?)",[\s\S]*?"skrl_cfg_entry_point":\s*f?"([^"]+?)"',
        re.MULTILINE
    )
    for _m in _pattern.finditer(_text):
        _id = _m.group(1)
        _env_cfg_ep = _m.group(2)
        _skrl_ep_raw = _m.group(3)
        # Build evaluated skrl entry point (handle f"{__name__}..." cases)
        _skrl_ep = _skrl_ep_raw
        _prefix = '{__name__}'
        if _skrl_ep.startswith(_prefix):
            _skrl_ep = __name__ + _skrl_ep[len(_prefix):]
        # Create flat variants
        _flat_id = _id.replace('-v0', '-Flat-v0')
        _flat_skrl_ep = _skrl_ep.replace('skrl_ppo_l1_cfg.yaml', 'skrl_ppo_cfg.yaml')
        try:
            gym.register(
                id=_flat_id,
                entry_point="isaaclab.envs:ManagerBasedRLEnv",
                kwargs={
                    "env_cfg_entry_point": _env_cfg_ep,
                    "skrl_cfg_entry_point": _flat_skrl_ep,
                },
            )
        except Exception:
            # Ignore if already registered or if pattern misses
            pass
except Exception:
    # Be resilient if file access or regex fails
    pass
